# Site
name: "Engineer's Log"
title: "Engineer's Log"
description: "This is an internship log"
logo: 'assets/images/logo.svg'
favicon: 'assets/images/favicon.ico'
baseurl: /engineers-log
google_analytics: ''
disqus: ''
mailchimp-list: false
include: ["_pages"]
permalink: /:title/

# Comments
comments:
  page: false
  post: false

# Plugins
plugins:
  - jekyll-paginate-v2
  - jekyll-auto-authors
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives

gems:
  - jekyll-minifier
  - jekyll-related_posts
  - jekyll-mermaid

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
pagination:
  enabled: true
  debug: true
  per_page: 6
  collection: 'posts'
  sort_reverse: true
  permalink: /page:num/

autopages:
  enabled: true
  authors:
    enabled: true
    data: '_data/authors.yml' # Data file with the author details
    layouts: 
      - 'author.html' # We'll define this layout later
    title: ':author'
    permalink: '/author/:author/'
    slugify:
      mode: 'default' # choose from [raw, default, pretty, ascii or latin]
      cased: true # if true, the uppercase letters in slug will be converted to lowercase ones.

# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: 
- changelog.md
- LICENSE.txt
- README.md
- Gemfile
- Gemfile.lock

related:
  display: true

related_by: tags or categories
related_limit: 3
related_from: posts
related_categories: 2
related_tags: 1
related_template: related-post.html

